### ISSUE TITLE
May want to consider changing language???

### ISSUE THREAD

**Issue by brandonefields** [learn-co-curriculum/phase-0-pac-2-default-sequence-and-comments#1]
Recognize the Comment Marker
We can exclude a line from the default sequence by starting the line with the comment marker: //. After JavaScript sees a //, it will ignore from the // to the next line.

Be careful! A comment placed in the middle of an expression can confuse JavaScript.

// Don't do this:
const sum = ( 1 //+ 1);

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

Thanks for contributing to the Flatiron School curriculum. 💙
